students = [
			{:name => "Chloe", :cohort => :june, :hobby => football},
			{:name => "Toan", :cohort => :june, :hobby => football},
			{:name => "Nic", :cohort => :june, :hobby => football},
			{:name => "Iona", :cohort => :june, :hobby => football},
			{:name => "Joe", :cohort => :june, :hobby => football},
			{:name => "Tom", :cohort => :june, :hobby => football},
			{:name => "Charlotte", :cohort => :june, :hobby => football},
			{:name => "Lisa", :cohort => :june, :hobby => football},
			{:name => "Zoe", :cohort => :june, :hobby => football},
			{:name => "Eddie", :cohort => :june, :hobby => football},
			{:name => "Charlie", :cohort => :june, :hobby => football},
			{:name => "Jean", :cohort => :june, :hobby => football},
			{:name => "Igor", :cohort => :june, :hobby => football},
			{:name => "Hannah", :cohort => :june, :hobby => football},
			{:name => "Catharina", :cohort => :june, :hobby => football},
			{:name => "Michael", :cohort => :june, :hobby => football},
			{:name => "David", :cohort => :june, :hobby => football},
			{:name => "Jamie", :cohort => :june, :hobby => football},
			{:name => "Peter", :cohort => :june, :hobby => football},
			{:name => "Talal", :cohort => :june, :hobby => football},
			{:name => "Marco", :cohort => :june, :hobby => football},
			{:name => "Zana", :cohort => :june, :hobby => football},
			{:name => "Jenny", :cohort => :june, :hobby => football},
			{:name => "Nicola", :cohort => :june, :hobby => football},
			{:name => "Jeremy", :cohort => :june, :hobby => football}
		]